id: I1135CBB6
default_language: bo
source: ''
initial_creation_type: tmx
imported: 2022-12-14 10:37:09.024750+00:00
last_modified: 2022-12-14 10:37:09.024755+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-043-007
  eft-text-version: 1.1.10 2020
  title: Toh_70-The_Sutra_of_the_Question_of_Subahu-v1
bases:
  EA0D:
    source_metadata: null
    order: 1
    base_file: EA0D.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
